package com.arttrip.android.presentation.home.sub.datecountryresult.contract

import com.arttrip.android.core.model.enums.exhibition.ExhibitionStatus
import com.arttrip.android.domain.model.exhibition.Exhibition

data class DateCountryResultState(
    val location: String = "",
    val dateStr: String = "",
    val list: List<Exhibition> = mockExhibitionList,
)

val mockExhibitionList =
    listOf(
        Exhibition(
            id = 1,
            title = "모네: 빛을 그리다",
            posterUrl = "https://picsum.photos/seed/ex1/400/600",
            status = ExhibitionStatus.ONGOING,
            period = "2024.11.01 - 2025.02.28",
            hallName = "루브르 박물관",
            country = "프랑스",
            region = "",
            isBookmarked = false,
        ),
        Exhibition(
            id = 2,
            title = "피카소: 청색 시대",
            posterUrl = "https://picsum.photos/seed/ex2/400/600",
            status = ExhibitionStatus.ENDING_SOON,
            period = "2024.10.15 - 2024.12.15",
            hallName = "퐁피두 센터",
            country = "프랑스",
            region = "",
            isBookmarked = true,
        ),
        Exhibition(
            id = 3,
            title = "인상주의의 탄생",
            posterUrl = "https://picsum.photos/seed/ex3/400/600",
            status = ExhibitionStatus.UPCOMING,
            period = "2025.01.10 - 2025.04.30",
            hallName = "오르세 미술관",
            country = "프랑스",
            region = "",
            isBookmarked = false,
        ),
        Exhibition(
            id = 4,
            title = "르누아르: 행복의 화가",
            posterUrl = "https://picsum.photos/seed/ex4/400/600",
            status = ExhibitionStatus.ONGOING,
            period = "2024.12.01 - 2025.03.31",
            hallName = "마르모탕 미술관",
            country = "프랑스",
            region = "",
            isBookmarked = false,
        ),
        Exhibition(
            id = 5,
            title = "세잔: 사과와 오렌지",
            posterUrl = "https://picsum.photos/seed/ex5/400/600",
            status = ExhibitionStatus.ONGOING,
            period = "2024.11.20 - 2025.02.10",
            hallName = "그랑 팔레",
            country = "프랑스",
            region = "",
            isBookmarked = true,
        ),
        Exhibition(
            id = 6,
            title = "마티스: 색채의 혁명",
            posterUrl = "https://picsum.photos/seed/ex6/400/600",
            status = ExhibitionStatus.ENDING_SOON,
            period = "2024.09.01 - 2024.12.20",
            hallName = "퐁피두 센터",
            country = "프랑스",
            region = "",
            isBookmarked = false,
        ),
        Exhibition(
            id = 7,
            title = "드가: 무용수의 세계",
            posterUrl = "https://picsum.photos/seed/ex7/400/600",
            status = ExhibitionStatus.UPCOMING,
            period = "2025.02.01 - 2025.05.31",
            hallName = "오르세 미술관",
            country = "프랑스",
            region = "",
            isBookmarked = false,
        ),
        Exhibition(
            id = 8,
            title = "고갱: 타히티의 꿈",
            posterUrl = "https://picsum.photos/seed/ex8/400/600",
            status = ExhibitionStatus.ONGOING,
            period = "2024.10.01 - 2025.01.31",
            hallName = "루브르 박물관",
            country = "프랑스",
            region = "",
            isBookmarked = true,
        ),
        Exhibition(
            id = 9,
            title = "쇠라: 점묘법의 세계",
            posterUrl = "https://picsum.photos/seed/ex9/400/600",
            status = ExhibitionStatus.FINISHED,
            period = "2024.08.01 - 2024.11.30",
            hallName = "프티 팔레",
            country = "프랑스",
            region = "",
            isBookmarked = false,
        ),
        Exhibition(
            id = 10,
            title = "로댕: 생각하는 사람",
            posterUrl = "https://picsum.photos/seed/ex10/400/600",
            status = ExhibitionStatus.ONGOING,
            period = "2024.11.15 - 2025.03.15",
            hallName = "로댕 미술관",
            country = "프랑스",
            region = "",
            isBookmarked = false,
        ),
    )
